---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "API for kogger"
basePath: "/api"
tags:
- name: "Logs"
  description: "Endpoints for logs"
paths:
  /namespaces:
    get:
      tags:
      - "Logs"
      summary: "Get all namespaces"
      operationId: "getNamespaces"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "All namespaces retrieved successfully"
          schema:
            $ref: "#/definitions/NamespaceResponse"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /resources:
    get:
      tags:
      - "Logs"
      summary: "Get all resources in a namespace"
      operationId: "listResources"
      produces:
      - "application/json"
      parameters:
      - name: "namespace"
        in: "query"
        description: "Name of the namespace"
        required: true
        type: "string"
        x-exportParamName: "Namespace"
      - name: "resourceType"
        in: "query"
        description: "Type of the resource"
        required: false
        type: "string"
        x-exportParamName: "ResourceType"
        x-optionalDataType: "String"
      responses:
        "200":
          description: "All resources in the namespace retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResourcesList"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /resource:
    get:
      tags:
      - "Logs"
      summary: "Get all resources in a namespace"
      operationId: "getResource"
      produces:
      - "application/json"
      parameters:
      - name: "namespace"
        in: "query"
        description: "Name of the namespace"
        required: true
        type: "string"
        x-exportParamName: "Namespace"
      - name: "resourceType"
        in: "query"
        description: "Type of the resource"
        required: true
        type: "string"
        x-exportParamName: "ResourceType"
      - name: "name"
        in: "query"
        description: "Name of the resource"
        required: true
        type: "string"
        x-exportParamName: "Name"
      responses:
        "200":
          description: "Resource information retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResourceInfo"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /logs/{namespace}:
    get:
      tags:
      - "Logs"
      summary: "Get all logs"
      operationId: "getLogs"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "All logs retrieved successfully"
          schema:
            $ref: "#/definitions/LogResponse"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
definitions:
  ResourceInfo:
    type: "object"
    required:
    - "name"
    - "namespace"
    - "resourceType"
    - "status"
    properties:
      namespace:
        type: "string"
        description: "Namespace of the resource"
      resourceType:
        type: "string"
        description: "Type of the resource"
      name:
        type: "string"
        description: "Name of the resource"
      status:
        type: "string"
        description: "Status of the resource"
      information:
        type: "object"
        description: "Additional information about the resource"
        properties: {}
    example:
      namespace: "namespace"
      name: "name"
      information: "{}"
      resourceType: "resourceType"
      status: "status"
  NamespaceResponse:
    type: "object"
    required:
    - "namespaces"
    properties:
      namespaces:
        type: "array"
        items:
          $ref: "#/definitions/NamespaceInList"
    example:
      namespaces:
      - resourcesPath: "resourcesPath"
        name: "name"
      - resourcesPath: "resourcesPath"
        name: "name"
  ResourcesList:
    type: "object"
    required:
    - "namespace"
    - "resources"
    properties:
      namespace:
        type: "string"
        description: "Namespace of the resource"
      resources:
        type: "array"
        items:
          $ref: "#/definitions/ResourcesByType"
    example:
      namespace: "namespace"
      resources:
      - resources:
        - informationPath: "informationPath"
          name: "name"
        - informationPath: "informationPath"
          name: "name"
        resourceType: "pod"
      - resources:
        - informationPath: "informationPath"
          name: "name"
        - informationPath: "informationPath"
          name: "name"
        resourceType: "pod"
  ResourcesByType:
    type: "object"
    required:
    - "resourceType"
    - "resources"
    properties:
      resourceType:
        type: "string"
        example: "pod"
        description: "Type of the resource"
      resources:
        type: "array"
        items:
          $ref: "#/definitions/ResourcesInList"
    example:
      resources:
      - informationPath: "informationPath"
        name: "name"
      - informationPath: "informationPath"
        name: "name"
      resourceType: "pod"
  ResourcesInList:
    type: "object"
    required:
    - "informationPath"
    - "name"
    properties:
      name:
        type: "string"
        description: "Name of the resource"
      informationPath:
        type: "string"
        description: "Api path to get information for the resource"
    example:
      informationPath: "informationPath"
      name: "name"
  NamespaceInList:
    type: "object"
    required:
    - "name"
    - "resourcesPath"
    properties:
      name:
        type: "string"
        description: "Name of the namespace"
      resourcesPath:
        type: "string"
        description: "Api path to get resources for the namespace"
    example:
      resourcesPath: "resourcesPath"
      name: "name"
  LogResponse:
    type: "object"
    properties:
      Logs:
        type: "array"
        items:
          $ref: "#/definitions/Logs"
    example:
      Logs:
      - node: "node"
        pod: "pod"
        namespace: "namespace"
        logs: "logs"
        status: "status"
      - node: "node"
        pod: "pod"
        namespace: "namespace"
        logs: "logs"
        status: "status"
  Logs:
    type: "object"
    required:
    - "logs"
    - "namespace"
    - "node"
    - "pod"
    - "status"
    properties:
      namespace:
        type: "string"
        description: "Namespace of the pod"
      pod:
        type: "string"
        description: "Name of the pod"
      status:
        type: "string"
        description: "Status of the pod"
      node:
        type: "string"
        description: "Node where the pod is running"
      logs:
        type: "string"
        description: "Logs of the pod"
    example:
      node: "node"
      pod: "pod"
      namespace: "namespace"
      logs: "logs"
      status: "status"
  Response:
    type: "object"
    required:
    - "message"
    - "token"
    properties:
      token:
        type: "string"
      message:
        type: "string"
